[package]
name = "hcs-control"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
hcs-settings = { path = "../hcs-settings" }
hcs-security = { path = "../hcs-security" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
