//! The QA suite: the list of stages, and the result of running them.
//!
//! v2.0.0 kept the stage list in a PowerShell array on the host and the
//! scenario files on disk, with nothing checking that the two agreed. A
//! renamed scenario produced a stage that silently "skipped" and the run still
//! reported a pass count. So the list is data, parsed and validated here, and
//! the guest runner refuses to start if a scenario named in the manifest is
//! missing.
//!
//! The manifest is generated by `scripts/generate_qa_scenarios.py` and staged
//! into the image at `/usr/share/hcs/qa/suite.json`. The guest needs no network
//! and no host cooperation to run it.

use serde::{Deserialize, Serialize};
use std::fmt;

/// What kind of proof a stage produces.
///
/// This distinction is not cosmetic. v1's stages 17-18 were described as GUI
/// evidence while actually capturing a text console, because the ISO had no
/// compositor. Recording the evidence type per stage makes it impossible to
/// present a console capture as a desktop capture without the report saying so.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Evidence {
    /// A text console frame: boot messages, GRUB, the installer.
    Console,
    /// A frame from the running graphical session.
    Gui,
}

impl fmt::Display for Evidence {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Evidence::Console => write!(f, "console"),
            Evidence::Gui => write!(f, "gui"),
        }
    }
}

/// One stage: a name, what it proves, and the scenario that proves it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Stage {
    pub n: u32,
    pub name: String,
    pub evidence: Evidence,
    /// File name inside the scenario directory, e.g. `07-start-menu.json`.
    pub scenario: String,
    /// What a reviewer should look at in the capture. Written down because a
    /// PNG in a report is not evidence unless someone knows what to see.
    pub proves: String,
}

/// The whole suite.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Suite {
    pub version: String,
    pub stages: Vec<Stage>,
}

/// Why a manifest is not usable.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SuiteError {
    Empty,
    NotSequential { expected: u32, found: u32 },
    DuplicateCombo,
    MissingScenario { stage: u32, scenario: String },
    NoEvidence,
}

impl fmt::Display for SuiteError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SuiteError::Empty => write!(f, "the suite has no stages"),
            SuiteError::NotSequential { expected, found } => write!(
                f,
                "stage numbering must run 1..N without gaps: expected {expected}, found {found}"
            ),
            SuiteError::DuplicateCombo => write!(f, "a scenario file is used by two stages"),
            SuiteError::MissingScenario { stage, scenario } => write!(
                f,
                "stage {stage} names scenario '{scenario}', which is not in the suite directory"
            ),
            SuiteError::NoEvidence => write!(f, "the suite declares no GUI evidence stages"),
        }
    }
}

impl Suite {
    pub fn parse(text: &str) -> Result<Suite, serde_json::Error> {
        serde_json::from_str(text)
    }

    /// Structural checks that do not need the filesystem.
    ///
    /// `available` is the set of scenario files actually present in the image.
    pub fn validate(&self, available: &[String]) -> Result<(), SuiteError> {
        if self.stages.is_empty() {
            return Err(SuiteError::Empty);
        }
        for (i, s) in self.stages.iter().enumerate() {
            let expected = i as u32 + 1;
            if s.n != expected {
                return Err(SuiteError::NotSequential {
                    expected,
                    found: s.n,
                });
            }
            if s.name.trim().is_empty() {
                return Err(SuiteError::NotSequential {
                    expected,
                    found: s.n,
                });
            }
        }
        // One scenario may legitimately back several stages (a boot produces
        // several console frames), but each stage must point at a file that
        // exists, and no *stage* may be duplicated.
        let mut seen: Vec<&str> = Vec::new();
        for s in &self.stages {
            if seen.contains(&s.name.as_str()) {
                return Err(SuiteError::DuplicateCombo);
            }
            seen.push(&s.name);
            if !available.iter().any(|a| a == &s.scenario) {
                return Err(SuiteError::MissingScenario {
                    stage: s.n,
                    scenario: s.scenario.clone(),
                });
            }
        }
        if !self.stages.iter().any(|s| s.evidence == Evidence::Gui) {
            return Err(SuiteError::NoEvidence);
        }
        Ok(())
    }

    pub fn gui_stages(&self) -> usize {
        self.stages
            .iter()
            .filter(|s| s.evidence == Evidence::Gui)
            .count()
    }

    pub fn console_stages(&self) -> usize {
        self.stages
            .iter()
            .filter(|s| s.evidence == Evidence::Console)
            .count()
    }
}

/// The verdict for one stage.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StageResult {
    pub stage: u32,
    pub name: String,
    pub evidence: Evidence,
    pub status: Status,
    /// Machine-readable reason for a failure, in the agent's own words.
    pub detail: String,
    /// Capture analysis, present when the stage produced a frame.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub capture: Option<crate::capture::CaptureReport>,
    /// How long the stage took, in milliseconds.
    pub duration_ms: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Status {
    Pass,
    Fail,
    /// The stage could not run: no scenario, or the agent was not authorised.
    Skipped,
}

impl fmt::Display for Status {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Status::Pass => write!(f, "PASS"),
            Status::Fail => write!(f, "FAIL"),
            Status::Skipped => write!(f, "SKIP"),
        }
    }
}

/// The suite-level result written to the evidence disk.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SuiteResult {
    pub version: String,
    pub profile: String,
    pub total: usize,
    pub passed: usize,
    pub failed: usize,
    pub skipped: usize,
    pub gui_stages: usize,
    pub console_stages: usize,
    /// Set when the run could not happen at all, e.g. the session never came up.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aborted: Option<String>,
    pub results: Vec<StageResult>,
    /// Every step of every stage, in order. A failure names its step.
    pub journal: Vec<crate::JournalEntry>,
}

impl SuiteResult {
    pub fn new(version: &str, profile: &str, suite: &Suite) -> Self {
        Self {
            version: version.to_string(),
            profile: profile.to_string(),
            total: suite.stages.len(),
            passed: 0,
            failed: 0,
            skipped: 0,
            gui_stages: suite.gui_stages(),
            console_stages: suite.console_stages(),
            aborted: None,
            results: Vec::new(),
            journal: Vec::new(),
        }
    }

    pub fn record(&mut self, r: StageResult) {
        match r.status {
            Status::Pass => self.passed += 1,
            Status::Fail => self.failed += 1,
            Status::Skipped => self.skipped += 1,
        }
        self.results.push(r);
    }

    /// True only when every stage passed. A run with skipped stages is not a
    /// pass: "we could not test this" and "this works" are different claims.
    pub fn is_green(&self) -> bool {
        self.aborted.is_none() && self.failed == 0 && self.skipped == 0
    }

    pub fn summary(&self) -> String {
        if let Some(why) = &self.aborted {
            return format!("ABORTED: {why}");
        }
        format!(
            "{}/{} stages PASS ({} GUI, {} console); {} failed, {} skipped",
            self.passed,
            self.total,
            self.gui_stages,
            self.console_stages,
            self.failed,
            self.skipped
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn stage(n: u32, name: &str, evidence: Evidence, scenario: &str) -> Stage {
        Stage {
            n,
            name: name.into(),
            evidence,
            scenario: scenario.into(),
            proves: "test".into(),
        }
    }

    fn suite(stages: Vec<Stage>) -> Suite {
        Suite {
            version: "2.0.0".into(),
            stages,
        }
    }

    fn all_files(s: &Suite) -> Vec<String> {
        s.stages.iter().map(|x| x.scenario.clone()).collect()
    }

    #[test]
    fn a_well_formed_suite_validates() {
        let s = suite(vec![
            stage(1, "grub_menu", Evidence::Console, "01.json"),
            stage(2, "desktop", Evidence::Gui, "02.json"),
        ]);
        assert_eq!(s.validate(&all_files(&s)), Ok(()));
        assert_eq!(s.gui_stages(), 1);
        assert_eq!(s.console_stages(), 1);
    }

    #[test]
    fn an_empty_suite_is_rejected() {
        let s = suite(vec![]);
        assert_eq!(s.validate(&[]), Err(SuiteError::Empty));
    }

    #[test]
    fn a_gap_in_the_numbering_is_rejected() {
        // v1 numbered 1..16 and then jumped; a reader counting stages could not
        // tell a gap from a deletion.
        let s = suite(vec![
            stage(1, "a", Evidence::Console, "a.json"),
            stage(3, "b", Evidence::Gui, "b.json"),
        ]);
        assert_eq!(
            s.validate(&all_files(&s)),
            Err(SuiteError::NotSequential {
                expected: 2,
                found: 3
            })
        );
    }

    #[test]
    fn a_missing_scenario_is_rejected_rather_than_skipped() {
        // This is the failure that let v1 report passes for stages it never ran.
        let s = suite(vec![
            stage(1, "a", Evidence::Console, "a.json"),
            stage(2, "b", Evidence::Gui, "gone.json"),
        ]);
        assert_eq!(
            s.validate(&["a.json".to_string()]),
            Err(SuiteError::MissingScenario {
                stage: 2,
                scenario: "gone.json".into()
            })
        );
    }

    #[test]
    fn a_duplicate_stage_name_is_rejected() {
        let s = suite(vec![
            stage(1, "a", Evidence::Console, "a.json"),
            stage(2, "a", Evidence::Gui, "a.json"),
        ]);
        assert_eq!(s.validate(&all_files(&s)), Err(SuiteError::DuplicateCombo));
    }

    #[test]
    fn a_suite_with_no_gui_stage_is_rejected() {
        // A run that only proves console frames is not the GUI gate, and must
        // not be able to call itself one.
        let s = suite(vec![stage(1, "a", Evidence::Console, "a.json")]);
        assert_eq!(s.validate(&all_files(&s)), Err(SuiteError::NoEvidence));
    }

    #[test]
    fn one_scenario_may_back_several_stages() {
        let s = suite(vec![
            stage(1, "boot_a", Evidence::Console, "boot.json"),
            stage(2, "boot_b", Evidence::Console, "boot.json"),
            stage(3, "desktop", Evidence::Gui, "desktop.json"),
        ]);
        assert_eq!(s.validate(&all_files(&s)), Ok(()));
    }

    #[test]
    fn skipped_stages_prevent_a_green_run() {
        let mut r = SuiteResult::new(
            "2.0.0",
            "edge",
            &suite(vec![stage(1, "a", Evidence::Gui, "a.json")]),
        );
        r.record(StageResult {
            stage: 1,
            name: "a".into(),
            evidence: Evidence::Gui,
            status: Status::Skipped,
            detail: "scenario missing".into(),
            capture: None,
            duration_ms: 0,
        });
        assert!(!r.is_green(), "a skipped stage is not a pass");
        assert_eq!(
            r.summary(),
            "0/1 stages PASS (1 GUI, 0 console); 0 failed, 1 skipped"
        );
    }

    #[test]
    fn an_abort_prevents_a_green_run_even_with_no_failures() {
        let r = SuiteResult {
            aborted: Some("session never came up".into()),
            ..SuiteResult::new("2.0.0", "edge", &suite(vec![]))
        };
        assert!(!r.is_green());
        assert_eq!(r.summary(), "ABORTED: session never came up");
    }

    #[test]
    fn a_full_pass_is_green() {
        let s = suite(vec![
            stage(1, "a", Evidence::Console, "a.json"),
            stage(2, "b", Evidence::Gui, "b.json"),
        ]);
        let mut r = SuiteResult::new("2.0.0", "edge", &s);
        for st in &s.stages {
            r.record(StageResult {
                stage: st.n,
                name: st.name.clone(),
                evidence: st.evidence,
                status: Status::Pass,
                detail: "ok".into(),
                capture: None,
                duration_ms: 10,
            });
        }
        assert!(r.is_green());
        assert_eq!(r.passed, 2);
    }

    #[test]
    fn the_manifest_round_trips() {
        let s = suite(vec![stage(7, "start_menu", Evidence::Gui, "07.json")]);
        let text = serde_json::to_string(&s).unwrap();
        assert_eq!(Suite::parse(&text).unwrap(), s);
    }
}
